// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class OhRockStudio
{
        public const string leaderboard__no5_kill_time_rank = "CgkI-_DYnssUEAIQHg"; // <GPGSID>
        public const string leaderboard__no10_kill_time_rank = "CgkI-_DYnssUEAIQGQ"; // <GPGSID>
        public const string achievement_ = "CgkI-_DYnssUEAIQBQ"; // <GPGSID>
        public const string leaderboard__no16_kill_time_rank = "CgkI-_DYnssUEAIQEw"; // <GPGSID>
        public const string achievement_12 = "CgkI-_DYnssUEAIQAg"; // <GPGSID>
        public const string leaderboard__no17_kill_time_rank = "CgkI-_DYnssUEAIQEg"; // <GPGSID>
        public const string leaderboard__no25_kill_time_rank = "CgkI-_DYnssUEAIQCg"; // <GPGSID>
        public const string leaderboard__no6_kill_time_rank = "CgkI-_DYnssUEAIQHQ"; // <GPGSID>
        public const string leaderboard__no11_kill_time_rank = "CgkI-_DYnssUEAIQGA"; // <GPGSID>
        public const string leaderboard__no0_kill_time_rank = "CgkI-_DYnssUEAIQIw"; // <GPGSID>
        public const string leaderboard__no12_kill_time_rank = "CgkI-_DYnssUEAIQFw"; // <GPGSID>
        public const string leaderboard__no1_kill_time_rank = "CgkI-_DYnssUEAIQIg"; // <GPGSID>
        public const string leaderboard__no4_kill_time_rank = "CgkI-_DYnssUEAIQHw"; // <GPGSID>
        public const string achievement_1 = "CgkI-_DYnssUEAIQAQ"; // <GPGSID>
        public const string leaderboard__no18_kill_time_rank = "CgkI-_DYnssUEAIQEQ"; // <GPGSID>
        public const string leaderboard__no26_kill_time_rank = "CgkI-_DYnssUEAIQCQ"; // <GPGSID>
        public const string leaderboard__no7_kill_time_rank = "CgkI-_DYnssUEAIQHA"; // <GPGSID>
        public const string leaderboard__no20_kill_time_rank = "CgkI-_DYnssUEAIQDw"; // <GPGSID>
        public const string leaderboard__no13_kill_time_rank = "CgkI-_DYnssUEAIQFg"; // <GPGSID>
        public const string leaderboard__no27kill_time_rank = "CgkI-_DYnssUEAIQCA"; // <GPGSID>
        public const string leaderboard__no21_kill_time_rank = "CgkI-_DYnssUEAIQDg"; // <GPGSID>
        public const string leaderboard__no2_kill_time_rank = "CgkI-_DYnssUEAIQIQ"; // <GPGSID>
        public const string leaderboard__no19_kill_time_rank = "CgkI-_DYnssUEAIQEA"; // <GPGSID>
        public const string leaderboard__no8_kill_time_rank = "CgkI-_DYnssUEAIQGw"; // <GPGSID>
        public const string leaderboard__no9_kill_time_rank = "CgkI-_DYnssUEAIQGg"; // <GPGSID>
        public const string leaderboard__no14_kill_time_rank = "CgkI-_DYnssUEAIQFQ"; // <GPGSID>
        public const string leaderboard__no22_kill_time_rank = "CgkI-_DYnssUEAIQDQ"; // <GPGSID>
        public const string leaderboard__no3_kill_time_rank = "CgkI-_DYnssUEAIQIA"; // <GPGSID>
        public const string leaderboard__no24_kill_time_rank = "CgkI-_DYnssUEAIQCw"; // <GPGSID>
        public const string leaderboard__no28_kill_time_rank = "CgkI-_DYnssUEAIQBw"; // <GPGSID>
        public const string leaderboard__no29_kill_time_rank = "CgkI-_DYnssUEAIQBg"; // <GPGSID>
        public const string leaderboard__no15_kill_time_rank = "CgkI-_DYnssUEAIQFA"; // <GPGSID>
        public const string achievement_2 = "CgkI-_DYnssUEAIQAw"; // <GPGSID>
        public const string leaderboard__no23_kill_time_rank = "CgkI-_DYnssUEAIQDA"; // <GPGSID>
        public const string achievement_5 = "CgkI-_DYnssUEAIQBA"; // <GPGSID>

}

