// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class SuperRoom
{
        public const string leaderboard__no5_kill_time_rank = "CgkI6tf649MWEAIQIA"; // <GPGSID>
        public const string leaderboard__no10_kill_time_rank = "CgkI6tf649MWEAIQGw"; // <GPGSID>
        public const string leaderboard__no16_kill_time_rank = "CgkI6tf649MWEAIQFA"; // <GPGSID>
        public const string leaderboard__no24_kill_time_rank = "CgkI6tf649MWEAIQDA"; // <GPGSID>
        public const string leaderboard__no17_kill_time_rank = "CgkI6tf649MWEAIQEw"; // <GPGSID>
        public const string leaderboard__no25_kill_time_rank = "CgkI6tf649MWEAIQCw"; // <GPGSID>
        public const string leaderboard__no6_kill_time_rank = "CgkI6tf649MWEAIQHw"; // <GPGSID>
        public const string leaderboard__no11_kill_time_rank = "CgkI6tf649MWEAIQGQ"; // <GPGSID>
        public const string leaderboard__no0_kill_time_rank = "CgkI6tf649MWEAIQJQ"; // <GPGSID>
        public const string leaderboard__no12_kill_time_rank = "CgkI6tf649MWEAIQGA"; // <GPGSID>
        public const string leaderboard__no1_kill_time_rank = "CgkI6tf649MWEAIQJA"; // <GPGSID>
        public const string leaderboard__no18_kill_time_rank = "CgkI6tf649MWEAIQEg"; // <GPGSID>
        public const string leaderboard__no26_kill_time_rank = "CgkI6tf649MWEAIQCg"; // <GPGSID>
        public const string leaderboard__no7_kill_time_rank = "CgkI6tf649MWEAIQHg"; // <GPGSID>
        public const string leaderboard__no20_kill_time_rank = "CgkI6tf649MWEAIQEA"; // <GPGSID>
        public const string leaderboard__no13_kill_time_rank = "CgkI6tf649MWEAIQFw"; // <GPGSID>
        public const string leaderboard__no21_kill_time_rank = "CgkI6tf649MWEAIQDw"; // <GPGSID>
        public const string leaderboard__no2_kill_time_rank = "CgkI6tf649MWEAIQIw"; // <GPGSID>
        public const string leaderboard__no19_kill_time_rank = "CgkI6tf649MWEAIQEQ"; // <GPGSID>
        public const string leaderboard__no27_kill_time_rank = "CgkI6tf649MWEAIQCQ"; // <GPGSID>
        public const string leaderboard__no8_kill_time_rank = "CgkI6tf649MWEAIQHQ"; // <GPGSID>
        public const string leaderboard__no9_kill_time_rank = "CgkI6tf649MWEAIQHA"; // <GPGSID>
        public const string leaderboard__no14_kill_time_rank = "CgkI6tf649MWEAIQFg"; // <GPGSID>
        public const string leaderboard__no22_kill_time_rank = "CgkI6tf649MWEAIQDg"; // <GPGSID>
        public const string leaderboard__no3_kill_time_rank = "CgkI6tf649MWEAIQIg"; // <GPGSID>
        public const string achievement_test1 = "CgkI6tf649MWEAIQAw"; // <GPGSID>
        public const string achievement_test2 = "CgkI6tf649MWEAIQBA"; // <GPGSID>
        public const string achievement_test3 = "CgkI6tf649MWEAIQBQ"; // <GPGSID>
        public const string achievement_test4 = "CgkI6tf649MWEAIQBg"; // <GPGSID>
        public const string achievement_test5 = "CgkI6tf649MWEAIQBw"; // <GPGSID>
        public const string leaderboard__no28_kill_time_rank = "CgkI6tf649MWEAIQCA"; // <GPGSID>
        public const string leaderboard__no29_kill_time_rank = "CgkI6tf649MWEAIQAQ"; // <GPGSID>
        public const string leaderboard__no15_kill_time_rank = "CgkI6tf649MWEAIQFQ"; // <GPGSID>
        public const string leaderboard__no23_kill_time_rank = "CgkI6tf649MWEAIQDQ"; // <GPGSID>
        public const string leaderboard__no4_kill_time_rank = "CgkI6tf649MWEAIQIQ"; // <GPGSID>

}

